---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.12.13

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1

driver_config:
  customize:
    cpus: 2
    memory: 1024

suites:
  - name: init
    run_list:
      - recipe[spring-boot::default]
      - recipe[spring-boot::example_init]
    attributes:
    verifier:
      inspec_tests:
        - test/recipes/example_init_test.rb
  - name: systemd
    run_list:
      - recipe[spring-boot::default]
      - recipe[spring-boot::example_systemd]
    attributes:
    verifier:
      inspec_tests:
        - test/recipes/example_systemd_test.rb
    excludes:
      - name: ubuntu-14.04
