driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: current
  ports:
    - 8080:8080

provisioner:
  name: dokken
  data_bags_path: ./data_bags

transport:
  name: dokken

verifier:
  name: inspec
platforms:
  - name: ubuntu-14.04
    driver:
      image: dokken/ubuntu-14.04
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
suites:
  - name: init
    run_list:
      - recipe[fake::example_init]
  - name: systemd
    run_list:
      - recipe[fake::example_systemd]
    excludes:
      - ubuntu-14.04
