---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36

platforms:
  - name: centos-7.2

driver_config:
  customize:
    cpus: 2
    memory: 1024

suites:
  - name: default
    run_list:
      - recipe[fake::default]
    attributes:
