sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

install: gem install rspec-retry

services: docker
jobs:
  include:
    - stage: style
      before_script:
        - eval "$(chef shell-init bash)"
        - chef --version
        - cookstyle --version
        - foodcritic --version
      script:
        - cookstyle .
        - foodcritic .
    - stage: itegration
      env:
        - KITCHEN_YAML=.kitchen.yml
        - INSTANCE=ubuntu-1404 SUITE=init
      before_script:
        - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
      script:
        - kitchen verify ${SUITE}-${INSTANCE}
    - stage: itegration
      env:
        - KITCHEN_YAML=.kitchen.yml
        - INSTANCE=ubuntu-1604 SUITE=systemd
      before_script:
        - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
      script:
        - kitchen verify ${SUITE}-${INSTANCE}
    - stage: itegration
      env:
        - KITCHEN_YAML=.kitchen.yml
        - INSTANCE=centos-7 SUITE=systemd
      before_script:
        - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
      script:
        - kitchen verify ${SUITE}-${INSTANCE}
